on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  CI: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '14'
      - name: Install
        run: npm install --no-package-lock
      - name: Test
        run: npm test
